# Generated by Django 5.2 on 2026-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "ادمین"), ("doctor", "پزشک"), ("secretary", "منشی")],
                default="doctor",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
    ]
