# Generated by Django 5.2 on 2026-04-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctor_picture"),
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reception",
            name="doctors",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receptionists",
                to="doctor.doctor",
                verbose_name="پزشکان تحت پوشش",
            ),
        ),
    ]
