# Generated by Django 5.2 on 2026-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_alter_doctor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
