# Generated by Django 5.2 on 2026-04-20 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_first_name",
                    models.CharField(max_length=100, verbose_name="نام بیمار"),
                ),
                (
                    "patient_last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی بیمار"),
                ),
                (
                    "patient_phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره موبایل باید 11 رقم و با 09 شروع شود",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تلفن بیمار",
                    ),
                ),
                (
                    "patient_national_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کدملی بیمار"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ نوبت")),
                ("time", models.TimeField(verbose_name="ساعت نوبت")),
                ("problem", models.TextField(blank=True, verbose_name="ساعت نوبت")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("confirmed", "تایید شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctor.doctor",
                        verbose_name="دکتر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت",
                "verbose_name_plural": "نوبت ها",
                "unique_together": {("doctor", "date", "time")},
            },
        ),
    ]
