# Generated by Django 5.2 on 2026-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="problem",
            field=models.TextField(blank=True, verbose_name="بیماری و مشکلات"),
        ),
    ]
