# Generated by Django 5.2 on 2026-04-25 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient_phone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="شماره موبایل باید 11 رقم و با 09 شروع شود",
                        regex="^09\\d{9}$",
                    )
                ],
                verbose_name="شماره تلفن بیمار",
            ),
        ),
    ]
