# Generated by Django 5.2 on 2026-04-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_patient_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
    ]
